apiVersion: v1
kind: Pod
metadata:
  name: pvc-dependency
  labels:
    example: 2-1
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      volumeMounts:
        - mountPath: "/logs"
          name: log-volume
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: random-generator-log