apiVersion: batch/v1
kind: Job
metadata:
  name: random-generator
spec:
  parallelism: 5 # 병렬로 실행될 수 있는 파드 개수
  template:
    metadata:
      name: random-generator
    spec:
      restartPolicy: OnFailure
      containers:
        - name: random-generator
          image: k8spatterns/random-generator:1.0
          command:
            - "java"
            - "-version"
            - "sleep 5"