apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    env: random-generator
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
  priorityClassName: high-priority