apiVersion: v1
kind: Pod
metadata:
  name: resource-request-limit
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi