apiVersion: v1
kind: Pod
metadata:
  name: pod-with-rediness-check
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      readinessProbe:
        exec:
          command:
            - "stat"
            - "/var/run/random-generator-ready"