apiVersion: v1
kind: Pod
metadata:
  name: random-generator
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # confidential=high 레이블을 가진 파드가 실행 중인 노드는 security-zone 레이블이 있어야 함
        - labelSelector:
            matchLabels:
              confidential: high
          topologyKey: security-zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: # 
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                confidential: none
            topologyKey: kubernetes.io/hostname
          weight: 100
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0