apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-generator
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: random-generator
              image: k8spatterns/random-generator:1.0
              command:
                - "java"
                - "-version"
          restartPolicy: OnFailure
  schedule: "*/3 * * * *"