apiVersion: v1
kind: Pod
metadata:
  name: post-start-hook
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - sleep 30 && echo "Wake up!" > /tmp/postStart_done