apiVersion: v1
kind: StatefulSet
metadata:
  name: rg # 파드의 접두어로 사용
spec:
  serviceName: random-generator
  replicas: 2
  selector:
    matchLabels:
      app: random-generator
  template:
    metadata:
      labels:
        app: random-generator
    spec:
      containers:
        - name: random-generator
          image: k8spatterns/random-generator:1.0
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /logs 
              name: logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Mi